# Generated by Django 5.1.6 on 2025-03-27 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ufc', '0004_fight_blue_url_fight_red_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_matchups', to='ufc.event')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_a_matchups', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_b_matchups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fight_selections', to='ufc.fight')),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchup_selections', to='matchups.matchup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='matchup',
            constraint=models.UniqueConstraint(fields=('event', 'user_a', 'user_b'), name='unique_users_per_event'),
        ),
        migrations.AddConstraint(
            model_name='matchup',
            constraint=models.CheckConstraint(condition=models.Q(('user_a__lte', models.F('user_b'))), name='ensure_user_a_less_than_user_b'),
        ),
        migrations.AddConstraint(
            model_name='selection',
            constraint=models.UniqueConstraint(fields=('matchup', 'fight', 'user'), name='unique_user_selection_per_fight_per_matchup'),
        ),
    ]
