# Generated by Django 5.1.6 on 2025-03-22 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0001_initial'),
        ('ufc', '0004_fight_blue_url_fight_red_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matchup',
            constraint=models.CheckConstraint(condition=models.Q(('creator__lt', models.F('opponent'))), name='ensure_creator_less_than_opponent'),
        ),
    ]
