# Generated by Django 5.1.6 on 2025-03-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0002_selectionresult'),
        ('ufc', '0005_event_headline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selectionresult',
            unique_together={('matchup', 'fight')},
        ),
    ]
