# Generated by Django 5.1.6 on 2025-03-23 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0003_remove_matchup_ensure_creator_less_than_opponent_and_more'),
        ('ufc', '0004_fight_blue_url_fight_red_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchup',
            name='unique_creator_and_opponent_per_event',
        ),
        migrations.RemoveConstraint(
            model_name='matchup',
            name='ensure_creator_less_than_opponent',
        ),
        migrations.RenameField(
            model_name='matchup',
            old_name='creator',
            new_name='user_a',
        ),
        migrations.RenameField(
            model_name='matchup',
            old_name='opponent',
            new_name='user_b',
        ),
        migrations.AddConstraint(
            model_name='matchup',
            constraint=models.UniqueConstraint(fields=('event', 'user_a', 'user_b'), name='unique_users_per_event'),
        ),
        migrations.AddConstraint(
            model_name='matchup',
            constraint=models.CheckConstraint(condition=models.Q(('user_a__lte', models.F('user_b'))), name='ensure_user_a_less_than_user_b'),
        ),
    ]
