# Generated by Django 5.1.6 on 2025-04-05 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('matchups', '0004_matchup_first_pick'), ('matchups', '0005_alter_matchup_first_pick'), ('matchups', '0006_remove_matchup_first_pick'), ('matchups', '0007_matchup_first_pick')]

    dependencies = [
        ('matchups', '0003_alter_selectionresult_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='first_pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
