# Generated by Django 5.1.6 on 2025-04-05 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0004_matchup_first_pick_squashed_0007_matchup_first_pick'),
        ('ufc', '0006_alter_fight_method_alter_fight_round_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='selection',
            name='unique_user_selection_per_fight_per_matchup',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='fighter',
        ),
        migrations.RemoveField(
            model_name='selection',
            name='user',
        ),
        migrations.AddField(
            model_name='selection',
            name='bet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='selection',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selection',
            name='dibs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dib_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selection',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selection',
            name='user_a_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_a_selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selection',
            name='user_b_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_b_selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selection',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddConstraint(
            model_name='selection',
            constraint=models.UniqueConstraint(fields=('matchup', 'fight'), name='unique_selection_per_fight_per_matchup'),
        ),
    ]
