# Generated by Django 5.1.6 on 2025-04-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0008_remove_selection_unique_user_selection_per_fight_per_matchup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='selected',
        ),
    ]
