# Generated by Django 5.1.6 on 2025-04-05 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0010_alter_selection_user_a_selection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='bet',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
    ]
