# Generated by Django 5.1.6 on 2025-04-17 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0012_matchupresult_delete_selectionresult_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchupResult',
        ),
    ]
