# Generated by Django 5.1.6 on 2025-02-21 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain only letters, numbers, and ./-/_ characters.', regex='^[\\w.-]+$')], verbose_name='username'),
        ),
    ]
