# Generated by Django 5.1.6 on 2025-04-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0009_remove_selection_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='user_a_selection',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='user_b_selection',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
