# Generated by Django 5.1.6 on 2025-02-22 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(choices=[('main', 'Main Card'), ('prelim', 'Prelims'), ('early', 'Early Prelims')], max_length=15)),
                ('order', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('weight_class', models.CharField(max_length=255)),
                ('blue_name', models.CharField(max_length=255)),
                ('blue_img', models.URLField(blank=True, null=True)),
                ('red_name', models.CharField(max_length=255)),
                ('red_img', models.URLField(blank=True, null=True)),
                ('winner', models.CharField(max_length=255, null=True)),
                ('method', models.CharField(max_length=255, null=True)),
                ('round', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UfcEvent',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='unique_name_and_date_per_event'),
        ),
        migrations.AddField(
            model_name='fight',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='ufc.event'),
        ),
        migrations.AddConstraint(
            model_name='fight',
            constraint=models.UniqueConstraint(fields=('event', 'blue_name', 'red_name'), name='unique_fight_per_event'),
        ),
        migrations.AddConstraint(
            model_name='fight',
            constraint=models.CheckConstraint(condition=models.Q(('winner__isnull', True), ('winner', models.F('blue_name')), ('winner', models.F('red_name')), _connector='OR'), name='winner_must_be_fighter'),
        ),
    ]
