# Generated by Django 5.1.6 on 2025-02-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc', '0002_event_fight_delete_ufcevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='round',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
