# Generated by Django 5.1.6 on 2025-02-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc', '0003_alter_fight_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='blue_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='red_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
