# Generated by Django 5.1.6 on 2025-04-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc', '0005_event_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fight',
            name='round',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fight',
            name='winner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
