# Generated by Django 5.1.6 on 2025-04-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc', '0007_event_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='card',
            field=models.CharField(choices=[('main', 'main'), ('prelim', 'prelim'), ('early', 'early')], max_length=15),
        ),
    ]
